---
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: monitoring-pool
  namespace: monitoring
spec:
  addresses:
    - 172.16.52.9/32
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: monitoring-l2
  namespace: monitoring
---
