apiVersion: v1
kind: LimitRange
metadata: 
  name: big-limit-range
spec:
  limits:
    - default:
        cpu: "2"
        memory: 10Gi
      defaultRequest:
        cpu: "2"
        memory: 10Gi
      max:
        cpu: "8"
        memory: 40Gi
      min:
        cpu: 500m
        memory: 512Mi
      type: Container
